#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common
lsof -n -P | grep 8080 
OPENSHIFT_REPO_DIR=$OPENSHIFT_HOMEDIR/app-root/runtime/repo

if [ ! -z "$OPENSHIFT_DIY_LOG_DIR" ]; then
	OPENSHIFT_DIY_LOG_DIR=$OPENSHIFT_LOG_DIR
fi
# Start apache if present
if [ -d "$OPENSHIFT_HOMEDIR/app-root/runtime/srv/httpd" ]; then
    $OPENSHIFT_HOMEDIR/app-root/runtime/srv/httpd/bin/apachectl start > $OPENSHIFT_LOG_DIR/server.log 2>&1 &
fi

if [[ `lsof -n -P | grep 8080` ]];then
	echo "we could close port 8080 for runing nginx"
	kill -9 `lsof -t -i :8080`
	echo "we  closed port 8080 for runing nginx"
	lsof -n -P | grep 8080
fi

if [ -d "${OPENSHIFT_HOMEDIR}/app-root/runtime/srv/nginx/sbin" ]; then
	nohup ${OPENSHIFT_HOMEDIR}/app-root/runtime/srv/nginx/sbin/nginx -c ${OPENSHIFT_HOMEDIR}/app-root/runtime/srv/nginx/conf/nginx.conf.template  > ${OPENSHIFT_LOG_DIR}/server-template.log 2>&1 &
	nohup ${OPENSHIFT_HOMEDIR}/app-root/runtime/srv/nginx/sbin/nginx -c ${OPENSHIFT_HOMEDIR}/app-root/runtime/srv/nginx/conf/nginx.conf  > ${OPENSHIFT_LOG_DIR}/server-template.log 2>&1 &
	#nohup ${OPENSHIFT_HOMEDIR}/app-root/data/nginx/sbin/nginx  -c ${OPENSHIFT_HOMEDIR}/app-root/data/nginx/conf/nginx.conf > ${OPENSHIFT_LOG_DIR}/server-template.log 2>&1 &   tail -f $OPENSHIFT_LOG_DIR/server-template.log
fi
# Start php-fm if present
if [ -d "${OPENSHIFT_HOMEDIR}/app-root/runtime/repo/srv/php-{PHP_VERSION}/sbin" ]; then
	nohup ${OPENSHIFT_HOMEDIR}/app-root/runtime/repo/srv/php-{PHP_VERSION}/sbin/php-fpm  > $OPENSHIFT_LOG_DIR/php_run.log 2>&1 &
	#nohup ${OPENSHIFT_HOMEDIR}/app-root/runtime/repo/srv/php-5.4.27/sbin/php-fpm > $OPENSHIFT_LOG_DIR/php_run.log 2>&1 & tail -f $OPENSHIFT_LOG_DIR/php_run.log
fi
# Start tornado if present
if [ -d "${OPENSHIFT_HOMEDIR}/app-root/runtime/srv/python/bin" ]; then
	nohup sh -c 'export PATH=${OPENSHIFT_HOMEDIR}/app-root/runtime/srv/python/bin:$PATH' > $OPENSHIFT_LOG_DIR/path_export2.log /dev/null 2>&1 & 
	export $PATH & tail -f $OPENSHIFT_LOG_DIR/path_export2.log

	nohup sh -c "${OPENSHIFT_HOMEDIR}/app-root/runtime/srv/python/bin/python ${OPENSHIFT_HOMEDIR}/app-root/runtime/srv/tornado3/tornado-get.py  --port '15001'" > ${OPENSHIFT_LOG_DIR}/tornado1.log /dev/null 2>&1 &
	
fi

# Start nginx if present
if [[ `lsof -n -P | grep 8080` ]];then
	kill -9 `lsof -t -i :8080`
	lsof -n -P | grep 8080
	nohup ${OPENSHIFT_HOMEDIR}/app-root/data/nginx/sbin/nginx  -c ${OPENSHIFT_HOMEDIR}/app-root/data/nginx/conf/nginx.conf > ${OPENSHIFT_LOG_DIR}/server-template.log  2>&1 &  
	lsof -n -P | grep 8080
fi
#Staring Fpm if present 
if [[ `lsof -n -P | grep 9000` ]];then
	kill -9 `lsof -t -i :9000`
	lsof -n -P | grep 9000
	nohup ${OPENSHIFT_HOMEDIR}/app-root/runtime/repo/srv/php-5.4.27/sbin/php-fpm > $OPENSHIFT_LOG_DIR/php_run.log 2>&1 
	lsof -n -P | grep 9000
fi

nohup sh -c "$OPENSHIFT_HOMEDIR/app-root/data/diy4ng4django4php/bin/python $OPENSHIFT_HOMEDIR/app-root/runti#me/srv/tornado/tornado-get.py -p 8080"\
 >  $OPENSHIFT_LOG_DIR/tornado_server18080.log 2>&1 &  tail -f $OPENSHIFT_DIY_LOG_DIR/tornado_server8080.log

 
